import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"
opacity = 0.98

[window.padding]
x = 4
y = 0
