code --install-extension bradlc.vscode-tailwindcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension miguelsolorio.fluent-icons
code --install-extension pkief.material-icon-theme
code --install-extension sdras.night-owl
code --install-extension svelte.svelte-vscode
code --install-extension vscodevim.vim
